services:
  # Postgres database for Inventory
  db-inventory:
    container_name: db-inventory
    image: postgres:15.5-alpine
    #restart: unless-stopped
    environment:
      POSTGRES_DB: db_inventory
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: docker123
    command: -p 5431
    ports:
      - 5431:5431
    expose:
      - 5431

  # mysql database for orders
  db-orders:
    container_name: db-orders
    image: mysql:8.4
    environment:
      MYSQL_DATABASE: db_orders
      MYSQL_USER: order_admin
      MYSQL_PASSWORD: docker123
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    expose:
      - 3306

  # postgres database for products
  db-products:
    container_name: db-products
    image: postgres:16.2-alpine
    environment:
      POSTGRES_DB: db_products
      POSTGRES_USER: products_admin
      POSTGRES_PASSWORD: docker123
    command: -p 5432
    ports:
      - 5432:5432
    expose:
      - 5432

  ### Postgres database for Keycloak
  db-keycloak:
    container_name: db-keycloak
    image: postgres:15.5-alpine
    #restart: unless-stopped
    environment:
      POSTGRES_DB: db_keycloak
      POSTGRES_USER: kcadmin
      POSTGRES_PASSWORD: docker123
    command: -p 5433
    ports:
      - 5433:5433
    expose:
      - 5433

  ### Keycloak
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:21.0.2
    command: ["start-dev"]
    ports:
      - 8181:8181
    expose:
      - 8181
    depends_on:
      - db-keycloak
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://db-keycloak:5433/db_keycloak
      KC_DB_SCHEMA: public
      KC_DB_USERNAME: kcadmin
      KC_DB_PASSWORD: docker123
      #KC_DB_URL_HOST: db-keycloak
      #KC_DB_URL_DATABASE: db_keycloak
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin1234
      KC_HTTP_PORT: 8181

  ### Zookeeper
  zookeeper:
    container_name: zookeeper
    image: confluentinc/cp-zookeeper:7.4.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  ### Kafka
  kafka:
    container_name: kafka
    image: confluentinc/cp-kafka:7.4.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1